import { CountryOutlets } from '../types/outlets';

// Credible, well-known outlets. Logos are optional; UI falls back gracefully.
export const COUNTRY_OUTLETS: CountryOutlets[] = [
  {
    countryCode: 'gh',
    countryName: 'Ghana',
    outlets: [
      { id: 'ghanaweb', name: 'GhanaWeb', url: 'https://www.ghanaweb.com/', logo: 'https://www.ghanaweb.com/favicon-32x32.png' },
      { id: 'myjoyonline', name: 'MyJoyOnline', url: 'https://www.myjoyonline.com/', logo: 'https://www.myjoyonline.com/wp-content/uploads/fbrfg/favicon-32x32.png' },
      { id: 'graphic-online', name: 'Graphic Online', url: 'https://www.graphic.com.gh/' },
      { id: 'citi-newsroom', name: 'Citi Newsroom', url: 'https://citinewsroom.com/' },
      { id: 'ghanaian-times', name: 'Ghanaian Times', url: 'https://ghanaiantimes.com.gh/', logo: 'https://ghanaiantimes.com.gh/wp-content/uploads/2022/06/cropped-cropped-GT-Icon-32x32.png' },
      { id: 'joy-news', name: 'Joy News', url: 'https://www.myjoyonline.com/tag/joy-news/' },
      { id: 'modernghana', name: 'ModernGhana', url: 'https://www.modernghana.com/' },
      { id: 'starrfm', name: 'Starr FM', url: 'https://starrfm.com.gh/' },
      { id: '3news', name: '3News', url: 'https://3news.com/' },
      { id: 'peacefmonline', name: 'Peace FM Online', url: 'https://www.peacefmonline.com/' },
    ],
  },
  {
    countryCode: 'us',
    countryName: 'United States',
    outlets: [
      { id: 'nyt', name: 'The New York Times', url: 'https://www.nytimes.com/' },
      { id: 'washpost', name: 'The Washington Post', url: 'https://www.washingtonpost.com/' },
      { id: 'wsj', name: 'The Wall Street Journal', url: 'https://www.wsj.com/' },
      { id: 'ap', name: 'Associated Press', url: 'https://apnews.com/' },
      { id: 'reuters', name: 'Reuters', url: 'https://www.reuters.com/' },
      { id: 'cnn', name: 'CNN', url: 'https://www.cnn.com/' },
      { id: 'abc', name: 'ABC News', url: 'https://abcnews.go.com/' },
      { id: 'nbc', name: 'NBC News', url: 'https://www.nbcnews.com/' },
      { id: 'cbs', name: 'CBS News', url: 'https://www.cbsnews.com/' },
      { id: 'latimes', name: 'Los Angeles Times', url: 'https://www.latimes.com/' },
    ],
  },
  {
    countryCode: 'gb',
    countryName: 'United Kingdom',
    outlets: [
      { id: 'bbc', name: 'BBC News', url: 'https://www.bbc.com/news' },
      { id: 'guardian', name: 'The Guardian', url: 'https://www.theguardian.com/uk' },
      { id: 'skynews', name: 'Sky News', url: 'https://news.sky.com/' },
      { id: 'telegraph', name: 'The Telegraph', url: 'https://www.telegraph.co.uk/' },
      { id: 'independent', name: 'The Independent', url: 'https://www.independent.co.uk/' },
      { id: 'ft', name: 'Financial Times', url: 'https://www.ft.com/' },
      { id: 'times', name: 'The Times', url: 'https://www.thetimes.co.uk/' },
      { id: 'mirror', name: 'Daily Mirror', url: 'https://www.mirror.co.uk/' },
      { id: 'sun', name: 'The Sun', url: 'https://www.thesun.co.uk/' },
      { id: 'metro', name: 'Metro', url: 'https://metro.co.uk/news/' },
    ],
  },
  {
    countryCode: 'ng',
    countryName: 'Nigeria',
    outlets: [
      { id: 'punch', name: 'Punch', url: 'https://punchng.com/' },
      { id: 'vanguard', name: 'Vanguard', url: 'https://www.vanguardngr.com/' },
      { id: 'guardian-ng', name: 'The Guardian Nigeria', url: 'https://guardian.ng/' },
      { id: 'channels', name: 'Channels TV', url: 'https://www.channelstv.com/' },
      { id: 'premium-times', name: 'Premium Times', url: 'https://www.premiumtimesng.com/' },
      { id: 'thisday', name: 'ThisDay', url: 'https://www.thisdaylive.com/' },
      { id: 'daily-trust', name: 'Daily Trust', url: 'https://dailytrust.com/' },
      { id: 'sahara', name: 'Sahara Reporters', url: 'https://saharareporters.com/' },
      { id: 'leadership', name: 'Leadership', url: 'https://leadership.ng/' },
      { id: 'thecable', name: 'The Cable', url: 'https://www.thecable.ng/' },
    ],
  },
  {
    countryCode: 'za',
    countryName: 'South Africa',
    outlets: [
      { id: 'news24', name: 'News24', url: 'https://www.news24.com/' },
      { id: 'timeslive', name: 'TimesLIVE', url: 'https://www.timeslive.co.za/' },
      { id: 'iol', name: 'IOL', url: 'https://www.iol.co.za/' },
      { id: 'ewn', name: 'Eyewitness News', url: 'https://ewn.co.za/' },
      { id: 'dailymaverick', name: 'Daily Maverick', url: 'https://www.dailymaverick.co.za/' },
      { id: 'mg', name: 'Mail & Guardian', url: 'https://mg.co.za/' },
      { id: 'sabc', name: 'SABC News', url: 'https://www.sabcnews.com/' },
      { id: 'enca', name: 'eNCA', url: 'https://www.enca.com/' },
      { id: 'businessday', name: 'Business Day', url: 'https://www.businesslive.co.za/bd/' },
      { id: 'sowetan', name: 'SowetanLIVE', url: 'https://www.sowetanlive.co.za/' },
    ],
  },
  {
    countryCode: 'ke',
    countryName: 'Kenya',
    outlets: [
      { id: 'nation', name: 'Daily Nation', url: 'https://nation.africa/kenya' },
      { id: 'standard', name: 'The Standard', url: 'https://www.standardmedia.co.ke/' },
      { id: 'star', name: 'The Star', url: 'https://www.the-star.co.ke/' },
      { id: 'citizen', name: 'Citizen Digital', url: 'https://citizen.digital/' },
      { id: 'kbc', name: 'KBC', url: 'https://www.kbc.co.ke/' },
      { id: 'capitalfm', name: 'Capital FM', url: 'https://www.capitalfm.co.ke/news/' },
      { id: 'tuko', name: 'Tuko', url: 'https://www.tuko.co.ke/' },
      { id: 'k24', name: 'K24', url: 'https://www.k24tv.co.ke/' },
      { id: 'business-daily', name: 'Business Daily', url: 'https://www.businessdailyafrica.com/' },
      { id: 'ntv', name: 'NTV Kenya', url: 'https://ntv.nation.co.ke/' },
    ],
  },
  {
    countryCode: 'ca',
    countryName: 'Canada',
    outlets: [
      { id: 'cbc', name: 'CBC News', url: 'https://www.cbc.ca/news' },
      { id: 'ctv', name: 'CTV News', url: 'https://www.ctvnews.ca/' },
      { id: 'global', name: 'Global News', url: 'https://globalnews.ca/' },
      { id: 'nationalpost', name: 'National Post', url: 'https://nationalpost.com/' },
      { id: 'globeandmail', name: 'The Globe and Mail', url: 'https://www.theglobeandmail.com/' },
      { id: 'torontostar', name: 'Toronto Star', url: 'https://www.thestar.com/' },
      { id: 'lapresse', name: 'La Presse', url: 'https://www.lapresse.ca/' },
      { id: 'radio-canada', name: 'Radio‑Canada', url: 'https://ici.radio-canada.ca/nouvelle' },
      { id: 'cp24', name: 'CP24', url: 'https://www.cp24.com/' },
      { id: 'citynews', name: 'CityNews', url: 'https://www.citynews.ca/' },
    ],
  },
  {
    countryCode: 'de',
    countryName: 'Germany',
    outlets: [
      { id: 'spiegel', name: 'Der Spiegel', url: 'https://www.spiegel.de/' },
      { id: 'zeit', name: 'Die Zeit', url: 'https://www.zeit.de/' },
      { id: 'faz', name: 'FAZ', url: 'https://www.faz.net/' },
      { id: 'sz', name: 'Süddeutsche Zeitung', url: 'https://www.sueddeutsche.de/' },
      { id: 'tagesschau', name: 'Tagesschau', url: 'https://www.tagesschau.de/' },
      { id: 'dw', name: 'Deutsche Welle', url: 'https://www.dw.com/' },
      { id: 'bild', name: 'BILD', url: 'https://www.bild.de/' },
      { id: 'handelsblatt', name: 'Handelsblatt', url: 'https://www.handelsblatt.com/' },
      { id: 'taz', name: 'taz', url: 'https://taz.de/' },
      { id: 'focus', name: 'FOCUS Online', url: 'https://www.focus.de/' },
    ],
  },
  {
    countryCode: 'fr',
    countryName: 'France',
    outlets: [
      { id: 'lemonde', name: 'Le Monde', url: 'https://www.lemonde.fr/' },
      { id: 'lefigaro', name: 'Le Figaro', url: 'https://www.lefigaro.fr/' },
      { id: 'france24', name: 'France 24', url: 'https://www.france24.com/' },
      { id: 'liberation', name: 'Libération', url: 'https://www.liberation.fr/' },
      { id: 'leparisien', name: 'Le Parisien', url: 'https://www.leparisien.fr/' },
      { id: 'lesechos', name: 'Les Échos', url: 'https://www.lesechos.fr/' },
      { id: 'rfi', name: 'RFI', url: 'https://www.rfi.fr/' },
      { id: 'franceinfo', name: 'franceinfo:', url: 'https://www.francetvinfo.fr/' },
      { id: 'lexpress', name: "L'Express", url: 'https://www.lexpress.fr/' },
      { id: 'mediapart', name: 'Mediapart', url: 'https://www.mediapart.fr/' },
    ],
  },
  {
    countryCode: 'in',
    countryName: 'India',
    outlets: [
      { id: 'thehindu', name: 'The Hindu', url: 'https://www.thehindu.com/' },
      { id: 'toi', name: 'The Times of India', url: 'https://timesofindia.indiatimes.com/' },
      { id: 'indianexpress', name: 'The Indian Express', url: 'https://indianexpress.com/' },
      { id: 'ht', name: 'Hindustan Times', url: 'https://www.hindustantimes.com/' },
      { id: 'ndtv', name: 'NDTV', url: 'https://www.ndtv.com/' },
      { id: 'wire', name: 'The Wire', url: 'https://thewire.in/' },
      { id: 'scroll', name: 'Scroll.in', url: 'https://scroll.in/' },
      { id: 'indiatoday', name: 'India Today', url: 'https://www.indiatoday.in/' },
      { id: 'economictimes', name: 'The Economic Times', url: 'https://economictimes.indiatimes.com/' },
      { id: 'livemint', name: 'Mint', url: 'https://www.livemint.com/' },
    ],
  },
  {
    countryCode: 'jp',
    countryName: 'Japan',
    outlets: [
      { id: 'nhk', name: 'NHK', url: 'https://www3.nhk.or.jp/nhkworld/en/news/' },
      { id: 'asahi', name: 'Asahi Shimbun', url: 'https://www.asahi.com/' },
      { id: 'yomiuri', name: 'Yomiuri Shimbun', url: 'https://www.yomiuri.co.jp/' },
      { id: 'mainichi', name: 'Mainichi', url: 'https://mainichi.jp/' },
      { id: 'nikkei', name: 'Nikkei', url: 'https://www.nikkei.com/' },
      { id: 'japantimes', name: 'The Japan Times', url: 'https://www.japantimes.co.jp/' },
      { id: 'kyodo', name: 'Kyodo News', url: 'https://english.kyodonews.net/' },
      { id: 'sankei', name: 'Sankei', url: 'https://www.sankei.com/' },
      { id: 'jiji', name: 'Jiji Press', url: 'https://www.jiji.com/' },
      { id: 'tokyoreporter', name: 'Tokyo Reporter', url: 'https://www.tokyoreporter.com/' },
    ],
  },
  {
    countryCode: 'au',
    countryName: 'Australia',
    outlets: [
      { id: 'abc-au', name: 'ABC News', url: 'https://www.abc.net.au/news' },
      { id: 'smh', name: 'The Sydney Morning Herald', url: 'https://www.smh.com.au/' },
      { id: 'theage', name: 'The Age', url: 'https://www.theage.com.au/' },
      { id: 'theaustralian', name: 'The Australian', url: 'https://www.theaustralian.com.au/' },
      { id: 'news-com-au', name: 'news.com.au', url: 'https://www.news.com.au/' },
      { id: 'sbs', name: 'SBS News', url: 'https://www.sbs.com.au/news' },
      { id: 'heraldsun', name: 'Herald Sun', url: 'https://www.heraldsun.com.au/' },
      { id: 'guardian-au', name: 'The Guardian Australia', url: 'https://www.theguardian.com/au' },
      { id: '9news', name: '9News', url: 'https://www.9news.com.au/' },
      { id: 'skynews-au', name: 'Sky News Australia', url: 'https://www.skynews.com.au/' },
    ],
  },
];
