import type { LucideIcon } from 'lucide-react-native';
import {
  Activity,
  Baby,
  Brain,
  Briefcase,
  CheckCircle2,
  Clapperboard,
  Crown,
  Cpu,
  Feather,
  FlaskConical,
  Gamepad2,
  GraduationCap,
  Handshake,
  Heart,
  Home,
  Landmark,
  Leaf,
  Lightbulb,
  LifeBuoy,
  MapPin,
  Music,
  Palette,
  Rocket,
  Share2,
  Sparkles,
  Star,
  Sun,
  TrendingUp,
  Trees,
  Trophy,
  UserPlus,
  Users,
  Utensils,
  Wheat,
  Puzzle,
} from 'lucide-react-native';

export type InterestSubcategoryDefinition = {
  readonly id: string;
  readonly label: string;
  readonly description?: string;
};

export type InterestCategoryDefinition = {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly icon: LucideIcon;
  readonly subcategories?: readonly InterestSubcategoryDefinition[];
};

export const INTEREST_LIBRARY: readonly InterestCategoryDefinition[] = [
  {
    id: 'general',
    label: 'Community Highlights',
    description: 'A little bit of everything happening across Akora.',
    icon: Sparkles,
  },
  {
    id: 'education',
    label: 'Education & Learning',
    description: 'Scholarships, study circles, and lifelong learning pathways.',
    icon: GraduationCap,
    subcategories: [
      // Expanded 20-domain education taxonomy (single category, rich subdomains)
      { id: 'education_scholarships', label: 'Scholarships & Funding', description: 'Bursaries, student loans, grants, stipends, and aid navigation.' },
      { id: 'education_exam_readiness', label: 'Exam & Entrance Prep', description: 'BECE, WASSCE, NSMQ prep, university entrance, aptitude & certification exams.' },
      { id: 'education_stem_foundations', label: 'STEM Foundations', description: 'Early science clubs, maker spaces, robotics leagues, tinkering labs.' },
      { id: 'education_mathematics_statistics', label: 'Mathematics & Statistics', description: 'Pure math, applied math, probability, statistics, Olympiad practice.' },
      { id: 'education_physics_astronomy', label: 'Physics & Astronomy', description: 'Mechanics, optics, astrophysics, space science, observational nights.' },
      { id: 'education_chemistry_materials', label: 'Chemistry & Materials', description: 'Organic, inorganic, analytical, materials science, lab safety.' },
      { id: 'education_biology_life_sciences', label: 'Biology & Life Sciences', description: 'Genetics, microbiology, ecology, biotech, life science fieldwork.' },
      { id: 'education_environment_earth', label: 'Environmental & Earth Sciences', description: 'Geology, climatology, hydrology, sustainability and field surveys.' },
      { id: 'education_computing_programming', label: 'Computing & Programming', description: 'Coding bootcamps, algorithms, mobile/web dev, version control.' },
      { id: 'education_data_ai', label: 'Data & AI', description: 'Data analysis, visualization, machine learning, AI ethics, LLMs.' },
      { id: 'education_engineering_design', label: 'Engineering & Design', description: 'Mechanical, electrical, civil, product design, CAD & prototyping.' },
      { id: 'education_business_management', label: 'Business & Management', description: 'Marketing, operations, strategy, organizational behavior, entrepreneurship.' },
      { id: 'education_finance_accounting', label: 'Finance & Accounting', description: 'Financial literacy, corporate finance, auditing, taxation, investing.' },
      { id: 'education_economics_policy', label: 'Economics & Policy', description: 'Micro/macro, development economics, public policy, econometrics.' },
      { id: 'education_law_governance', label: 'Law & Governance', description: 'Legal studies, constitutional law, civic education, regulatory frameworks.' },
      { id: 'education_social_sciences', label: 'Social Sciences & Humanities', description: 'Sociology, anthropology, history, philosophy, psychology, ethics.' },
      { id: 'education_arts_communication', label: 'Arts & Communication', description: 'Literature, creative writing, media literacy, public speaking, debate.' },
      { id: 'education_health_medicine', label: 'Health & Medical Sciences', description: 'Human anatomy, nursing prep, public health, first aid, medical careers.' },
      { id: 'education_agriculture_food', label: 'Agriculture & Food Systems', description: 'Crop science, agribusiness basics, food security, post-harvest handling.' },
      { id: 'education_teaching_training', label: 'Teaching Practice & CPD', description: 'Pedagogy, curriculum design, classroom tech, continuous development.' },
      { id: 'education_language_linguistics', label: 'Languages & Linguistics', description: 'Local Ghanaian languages, French, English mastery, translation, linguistics.' },
      { id: 'education_professional_vocational', label: 'Professional & Vocational Skills', description: 'TVET, apprenticeships (fashion, catering, carpentry), employability skills.' },
      { id: 'education_study_groups', label: 'Study Groups & Peer Learning', description: 'Campus tutorials, accountability circles, virtual study halls.' },
      { id: 'education_alumni_networks', label: 'Alumni & Mentorship Networks', description: 'Old student associations, NSMQ teams, peer & cross-generational mentoring.' },
    ],
  },
  {
    id: 'career',
    label: 'Career Growth',
    description: 'Level up your professional journey with peers and mentors.',
    icon: Briefcase,
    subcategories: [
      // Expanded 20-domain career taxonomy
      { id: 'career_planning_exploration', label: 'Career Planning & Exploration', description: 'Discover paths, assess strengths, align personality, research markets, and map transitions.' },
      { id: 'career_professional_development', label: 'Professional Development', description: 'Leadership, productivity, strategy, decision-making, EQ, adaptability, conflict & problem solving.' },
      { id: 'career_communication_interpersonal', label: 'Communication & Interpersonal', description: 'Verbal/written comms, negotiation, public speaking, teamwork, networking, active listening.' },
      { id: 'career_technical_digital', label: 'Technical & Digital Skills', description: 'Data, software, cloud, AI/ML, cybersecurity, PM tools, UX/UI, digital marketing, product mgmt.' },
      { id: 'career_business_entrepreneurship', label: 'Business & Entrepreneurship Growth', description: 'Startup building, strategy, market research, finance, branding, sales, growth & e-commerce.' },
      { id: 'career_advancement_leadership', label: 'Career Advancement & Leadership', description: 'Career laddering, team leadership, performance mgmt, org leadership, influence & authority.' },
      { id: 'career_personal_growth_mindset', label: 'Personal Growth & Mindset', description: 'Confidence, resilience, growth mindset, motivation, focus, productivity, stress & balance.' },
      { id: 'career_continuous_learning', label: 'Continuous Learning & Upskilling', description: 'Lifelong learning, certs, research skills, new tools, workshops, knowledge sharing.' },
      { id: 'career_branding_marketing', label: 'Career Branding & Personal Marketing', description: 'CV/Resume, LinkedIn, personal brand, portfolio, digital identity, thought leadership.' },
      { id: 'career_finance_workplace_success', label: 'Financial & Workplace Success', description: 'Salary negotiation, budgeting, taxes/benefits, etiquette, promotions, retirement, side hustles.' },
      { id: 'career_job_search_employment', label: 'Job Search & Employment', description: 'Hunting strategies, interviews, internships, remote/freelance, applications & visas.' },
      { id: 'career_industry_specific', label: 'Industry-Specific Growth', description: 'Tech, health, business/finance, education, creative, engineering, media, legal, agri, tourism.' },
      { id: 'career_workplace_productivity', label: 'Workplace Skills & Productivity', description: 'Prioritisation, goals, process optimisation, remote/collab tools, meetings & email etiquette.' },
      { id: 'career_innovation_strategy', label: 'Innovation & Strategic Thinking', description: 'Design thinking, creative problem solving, product innovation, systems & business model design.' },
      { id: 'career_mentorship_networking', label: 'Mentorship & Networking', description: 'Find/be a mentor, alumni links, associations, events, relationship building & etiquette.' },
      { id: 'career_coaching_self_evaluation', label: 'Career Coaching & Self-Evaluation', description: 'Self-assessment, SMART goals, development plans, feedback, accountability & progress.' },
      { id: 'career_work_life_integration', label: 'Work-Life Integration', description: 'Remote balance, burnout care, healthy habits, family alignment, rest & boundaries.' },
      { id: 'career_global_cross_border', label: 'Global & Cross-Border Careers', description: 'International markets, work abroad, cultural intelligence, remote global teams, exchanges.' },
      { id: 'career_diversity_equity_inclusion', label: 'Diversity, Equity & Inclusion', description: 'Inclusive leadership, accessibility, diverse hiring, CSR, allyship & equal opportunity.' },
      { id: 'career_resilience_future_readiness', label: 'Career Resilience & Future Readiness', description: 'Automation, uncertainty, re/skilling, transferable skills, gig economy, sustainable careers.' },
    ],
  },
  {
    id: 'technology',
    label: 'Technology & Innovation',
    description: 'Build, ship, and explore the next wave of digital breakthroughs.',
    icon: Cpu,
    subcategories: [
      // Expanded 20-domain technology & innovation taxonomy
      { id: 'technology_ai_ml', label: 'AI & Machine Learning', description: 'AI, ML, DL, NLP, CV, neural networks, RL, generative AI, ethics & applied AI in sectors.' },
      { id: 'technology_software_engineering', label: 'Software Development & Engineering', description: 'Frontend, backend, full-stack, mobile, game dev, QA, architecture, DevOps, APIs, OSS.' },
      { id: 'technology_web_internet', label: 'Web & Internet Technologies', description: 'Web dev, PWAs, Web3/dApps, SEO/analytics, web security, e-commerce, infrastructure, CMS.' },
      { id: 'technology_cloud_infrastructure', label: 'Cloud Computing & Infrastructure', description: 'Cloud architecture, security, serverless, containers, databases, edge, networking, hybrid.' },
      { id: 'technology_data_science_analytics', label: 'Data Science & Analytics', description: 'Analysis, viz, data engineering, BI, big data, predictive analytics, stats, governance.' },
      { id: 'technology_cybersecurity_privacy', label: 'Cybersecurity & Privacy', description: 'Ethical hacking, network/cloud security, pen-testing, forensics, IAM, compliance, privacy.' },
      { id: 'technology_robotics_automation', label: 'Robotics & Automation', description: 'Robotics, industrial automation, drones, mechatronics, HRI, RPA, AVs, IIoT.' },
      { id: 'technology_iot', label: 'Internet of Things (IoT)', description: 'Smart homes/cities, sensors, embedded, wearables, connected vehicles, edge & industrial IoT.' },
      { id: 'technology_hardware_electronics', label: 'Hardware & Electronics', description: 'Hardware design, MCUs/MPUs, circuits/PCB, embedded, semiconductors, prototyping, EE basics.' },
      { id: 'technology_space_aerospace', label: 'Space, Aerospace & Defense', description: 'Satellites, aerospace engineering, space robotics, rockets, sensing, defense, UAVs, space data.' },
      { id: 'technology_engineering_industrial', label: 'Engineering & Industrial Innovation', description: 'Mechanical, civil/structural, power systems, chemical process, smart manufacturing, CAD/CAM.' },
      { id: 'technology_emerging', label: 'Emerging Technologies', description: 'Blockchain/crypto, Web3/DeFi, metaverse, AR/VR/MR, quantum, bioinformatics, neurotech, nano, twins.' },
      { id: 'technology_innovation_entrepreneurship', label: 'Innovation & Entrepreneurship', description: 'Design thinking, product innovation, startups, lean/MVP, IP, commercialization, R&D, open collab.' },
      { id: 'technology_research_development', label: 'Research & Development (R&D)', description: 'Research methods, experiments, prototyping/testing, labs, tech transfer, funding & ethics.' },
      { id: 'technology_sustainable_green', label: 'Sustainable & Green Tech', description: 'Renewables, green engineering, climate tech, smart ag, circular economy, carbon, clean water.' },
      { id: 'technology_digital_transformation', label: 'Digital Transformation & Future of Work', description: 'Automation in business, Industry 4.0, smart cities, human-AI collaboration, inclusion & tools.' },
      { id: 'technology_policy_ethics', label: 'Technology Policy & Ethics', description: 'Tech regulation, digital rights, AI fairness, data sovereignty, ethical innovation, cyberlaw.' },
      { id: 'technology_education_skills', label: 'Technology Education & Skills', description: 'Bootcamps, STEM, EdTech, maker/DIY, open learning, online tools, mentorship, women in tech.' },
      { id: 'technology_corporate_industrial', label: 'Corporate & Industrial Innovation', description: 'Innovation labs, product strategy, BPA, ecosystems, digital strategy, agile change & culture.' },
      { id: 'technology_global_trends', label: 'Global Technology Trends', description: 'Startups & ecosystems, mobility, 5G, wearables, digital health, FinTech, GovTech, civic impact.' },
    ],
  },
  {
    id: 'innovation',
    label: 'Innovation & Futures',
    description: 'Moonshots, emerging trends, and speculative technologies.',
    icon: Rocket,
    subcategories: [
      { id: 'innovation_future_trends', label: 'Future Trends & Foresight', description: 'Scenario planning and horizon scanning for Africa.' },
      { id: 'innovation_design', label: 'Innovation Design Labs', description: 'Design thinking sprints and co-creation studios.' },
      { id: 'innovation_social', label: 'Social Innovation', description: 'Community-driven solutions for health, education, and livelihoods.' },
      { id: 'innovation_corporate', label: 'Corporate Innovation', description: 'Intrapreneurship, venture studios, and corporate labs.' },
      { id: 'innovation_agritech', label: 'Agritech & Food Systems', description: 'Smart farming pilots, value chain digitisation, and logistics.' },
    ],
  },
  {
    id: 'entrepreneurship',
    label: 'Entrepreneurship',
    description: 'From idea to launch—support for builders at every stage.',
    icon: Lightbulb,
    subcategories: [
      { id: 'entrepreneurship_startups', label: 'Startup Playbooks', description: 'Customer discovery, MVP feedback, and founder stories.' },
      { id: 'entrepreneurship_small_business', label: 'Small Business Builders', description: 'Retail, services, and MSME growth toolkits.' },
      { id: 'entrepreneurship_social_enterprise', label: 'Social Enterprise', description: 'Mission-led ventures and impact business models.' },
      { id: 'entrepreneurship_funding', label: 'Fundraising & Capital', description: 'Angel networks, venture readiness, and grant pipelines.' },
      { id: 'entrepreneurship_growth', label: 'Scaling & Growth', description: 'Operations, hiring, and governance for growing teams.' },
      { id: 'entrepreneurship_agritech', label: 'Agritech Ventures', description: 'Mechanisation services, inputs delivery, and crop marketplaces.' },
      { id: 'entrepreneurship_creative', label: 'Creative Economy Founders', description: 'Fashion houses, music labels, and film production studios.' },
    ],
  },
  {
    id: 'finance',
    label: 'Money & Finance',
    description: 'Investing, budgeting, and building wealth responsibly.',
    icon: TrendingUp,
    subcategories: [
      { id: 'finance_budgeting', label: 'Budgeting & Habits', description: 'Susu groups, budgeting templates, and lifestyle planning.' },
      { id: 'finance_investing', label: 'Investing & Markets', description: 'GSE updates, treasury bills, and alternative assets.' },
      { id: 'finance_fintech', label: 'Fintech & Digital Finance', description: 'Mobile money, digital wallets, and embedded finance.' },
      { id: 'finance_retirement', label: 'Retirement & Pensions', description: 'Tiered pensions, provident funds, and retirement calculators.' },
      { id: 'finance_social_impact', label: 'Impact & Ethical Finance', description: 'ESG investing, green bonds, and social funding models.' },
      { id: 'finance_susu', label: 'Co-ops & Susu Culture', description: 'Village savings groups, credit unions, and microfinance tips.' },
      { id: 'finance_remittances', label: 'Remittances & Diaspora Money', description: 'Sending money home, FX rates, and diaspora investment clubs.' },
    ],
  },
  {
    id: 'health',
    label: 'Health & Care',
    description: 'Clinical care, wellness tips, and access to health resources.',
    icon: Heart,
    subcategories: [
      { id: 'health_preventive_care', label: 'Preventive Care', description: 'Screening programmes, NHIS updates, and health literacy.' },
      { id: 'health_public_health', label: 'Public & Community Health', description: 'Immunisation drives, sanitation campaigns, and CHPS compounds.' },
      { id: 'health_clinics', label: 'Clinics & Practitioners', description: 'Find specialists, telehealth services, and hospital reviews.' },
      { id: 'health_family_care', label: 'Family & Primary Care', description: 'Maternal health, infant care, and community midwives.' },
      { id: 'health_research', label: 'Health Research & Innovation', description: 'Clinical trials, healthtech pilots, and medical research hubs.' },
      { id: 'health_telemedicine', label: 'Telemedicine & Digital Health', description: 'Virtual consults, digital records, and health apps.' },
    ],
  },
  {
    id: 'mental_health',
    label: 'Mind & Balance',
    description: 'Mindfulness, resilience, and mental health resources.',
    icon: Brain,
    subcategories: [
      { id: 'mental_mindfulness', label: 'Mindfulness Practices', description: 'Meditation, breathwork, and presence exercises.' },
      { id: 'mental_therapy', label: 'Therapy & Coaching', description: 'Counsellors, psychologists, and pastoral care leads.' },
      { id: 'mental_resilience', label: 'Resilience & Coping', description: 'Support groups, trauma healing, and life transitions.' },
      { id: 'mental_emotional_intelligence', label: 'Emotional Intelligence', description: 'Workshops on empathy, conflict, and inner work.' },
      { id: 'mental_peer_support', label: 'Peer Support Circles', description: 'Safe spaces for students, creatives, and founders.' },
      { id: 'mental_faith_wellness', label: 'Faith & Wellness Intersections', description: 'Integrating spirituality and mental wellbeing.' },
    ],
  },
  {
    id: 'leadership',
    label: 'Leadership',
    description: 'Shape strategy, steward teams, and lead with impact.',
    icon: Crown,
    subcategories: [
      { id: 'leadership_strategy', label: 'Strategy & Vision', description: 'Strategic planning, OKRs, and vision casting.' },
      { id: 'leadership_team_building', label: 'Team Building', description: 'Culture design, trust-building, and team rituals.' },
      { id: 'leadership_change', label: 'Change Management', description: 'Transformation programmes, mergers, and integration.' },
      { id: 'leadership_innovation', label: 'Innovation Leadership', description: 'Leading labs, product councils, and experimentation.' },
      { id: 'leadership_public_service', label: 'Public Service Leadership', description: 'Governance, civic duty, and social leadership.' },
      { id: 'leadership_board_governance', label: 'Boards & Governance', description: 'Board best practices, compliance, and stewardship.' },
    ],
  },
  {
    id: 'volunteering',
    label: 'Service & Volunteering',
    description: 'Roll up your sleeves and serve communities together.',
    icon: LifeBuoy,
    subcategories: [
      { id: 'volunteering_local', label: 'Local Service Projects', description: 'Clean-up drives, reading clinics, and neighbourhood care.' },
      { id: 'volunteering_global', label: 'Global Missions & Outreach', description: 'International mission trips and diaspora collaborations.' },
      { id: 'volunteering_events', label: 'Event Support Crews', description: 'Conference volunteers, production teams, and ushers.' },
      { id: 'volunteering_youth', label: 'Youth & Education Programs', description: 'Mentoring, coaching, and after-school initiatives.' },
      { id: 'volunteering_sanitation', label: 'Sanitation & Clean-up', description: 'Beach cleanups, recycling drives, and environmental care.' },
      { id: 'volunteering_relief', label: 'Relief & Emergency Response', description: 'Humanitarian relief, blood drives, and disaster response.' },
    ],
  },
  {
    id: 'philanthropy',
    label: 'Philanthropy & Impact',
    description: 'Giving circles, fundraising, and impact-driven initiatives.',
    icon: Handshake,
    subcategories: [
      { id: 'philanthropy_fundraising', label: 'Fundraising Campaigns', description: 'Donation drives, crowdfunding, and pledge campaigns.' },
      { id: 'philanthropy_grantmaking', label: 'Grantmaking & Review', description: 'Grant committees, due diligence, and programme audits.' },
      { id: 'philanthropy_board', label: 'Board & Governance', description: 'NGO boards, accountability, and fiduciary stewardship.' },
      { id: 'philanthropy_impact_investing', label: 'Impact Investing', description: 'Social enterprise investments and blended finance.' },
      { id: 'philanthropy_storytelling', label: 'Impact Storytelling', description: 'Documenting change, reporting, and donor updates.' },
      { id: 'philanthropy_diaspora', label: 'Diaspora Giving', description: 'Returnee and diaspora-led fundraising and giving circles.' },
    ],
  },
  {
    id: 'sustainability',
    label: 'Sustainability',
    description: 'Climate action, green design, and ethical stewardship.',
    icon: Leaf,
    subcategories: [
      { id: 'sustainability_climate', label: 'Climate Action', description: 'Climate advocacy, policy, and adaptation efforts.' },
      { id: 'sustainability_energy', label: 'Clean Energy', description: 'Solar, mini-grids, and sustainable energy ventures.' },
      { id: 'sustainability_conservation', label: 'Conservation & Biodiversity', description: 'Forest, marine, and wildlife preservation.' },
      { id: 'sustainability_circular', label: 'Circular Economy', description: 'Recycling, upcycling, and zero-waste innovations.' },
      { id: 'sustainability_policy', label: 'Policy & Advocacy', description: 'Climate justice campaigns and civic action.' },
      { id: 'sustainability_agroforestry', label: 'Agroforestry & Land Use', description: 'Tree planting, community forests, and land restoration.' },
      { id: 'sustainability_plastics', label: 'Plastics & Waste Reduction', description: 'Plastic alternatives, clean coastline projects, and recycling.' },
    ],
  },
  {
    id: 'environment',
    label: 'Environment & Nature',
    description: 'Ecology, conservation, and living in rhythm with nature.',
    icon: Trees,
    subcategories: [
      { id: 'environment_ecology', label: 'Ecology & Research', description: 'Biodiversity studies and environmental science.' },
      { id: 'environment_urban', label: 'Urban Greening', description: 'City parks, tree planting, and green infrastructure.' },
      { id: 'environment_wildlife', label: 'Wildlife Protection', description: 'Habitat protection, rangers, and wildlife corridors.' },
      { id: 'environment_regenerative', label: 'Regenerative Practices', description: 'Regenerative agriculture and soil restoration.' },
      { id: 'environment_coastal', label: 'Coastal & Marine Health', description: 'Coastal erosion response and marine conservation.' },
      { id: 'environment_savannah', label: 'Savannah & Forest Landscapes', description: 'Northern Ghana landscapes, reserves, and rewilding.' },
    ],
  },
  {
    id: 'agriculture',
    label: 'Agriculture & Food Systems',
    description: 'From cocoa farms to agritech, grow the backbone of Ghana’s economy.',
    icon: Wheat,
    subcategories: [
      { id: 'agriculture_cocoa', label: 'Cocoa & Tree Crops', description: 'Farmer cooperatives, value addition, and certification.' },
      { id: 'agriculture_smallholder', label: 'Smallholder Farmers', description: 'Input access, extension services, and aggregation.' },
      { id: 'agriculture_agritech', label: 'Agritech Solutions', description: 'Digital advisory, marketplace platforms, and precision farming.' },
      { id: 'agriculture_processing', label: 'Processing & Value Addition', description: 'Agro-processing, storage, and cold chain solutions.' },
      { id: 'agriculture_markets', label: 'Agro Markets & Trade', description: 'Commodity pricing, export logistics, and market linkages.' },
      { id: 'agriculture_fisheries', label: 'Fisheries & Aquaculture', description: 'Inland fishing, aquaculture hubs, and blue economy ventures.' },
    ],
  },
  {
    id: 'science',
    label: 'Science & Research',
    description: 'Experiments, labs, and discoveries shaping our world.',
    icon: FlaskConical,
    subcategories: [
      { id: 'science_space', label: 'Space & Astronomy', description: 'Space science, satellite data, and astronomy clubs.' },
      { id: 'science_biotech', label: 'Biotech & Life Sciences', description: 'Biotech labs, genetics, and pharmaceutical research.' },
      { id: 'science_psychology', label: 'Psychology & Behaviour', description: 'Human behaviour research and social science labs.' },
      { id: 'science_policy', label: 'Science Policy', description: 'Evidence-based policy, think tanks, and research translation.' },
      { id: 'science_citizen', label: 'Citizen Science', description: 'Community research, data collection, and science outreach.' },
      { id: 'science_agriculture', label: 'Agricultural Science', description: 'Crop science, soil labs, and agri research stations.' },
      { id: 'science_health', label: 'Medical & Public Health Research', description: 'Clinical studies, epidemiology, and health informatics.' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Adventures',
    description: 'Global journeys, cultural exchanges, and trip planning.',
    icon: MapPin,
    subcategories: [
      { id: 'travel_cultural_exchange', label: 'Cultural Exchange', description: 'Diaspora return programmes and cultural immersion.' },
      { id: 'travel_service', label: 'Service & Mission Trips', description: 'Mission outreaches and volunteer travel itineraries.' },
      { id: 'travel_remote_work', label: 'Remote Work & Nomads', description: 'Co-living, workation hubs, and beachside offices.' },
      { id: 'travel_family', label: 'Family Travel', description: 'Family-friendly trips, staycations, and road trips.' },
      { id: 'travel_adventure', label: 'Adventure Travel', description: 'Safari excursions, paragliding, and thrill-seeking expeditions.' },
      { id: 'travel_city_guides', label: 'City Guides & Tips', description: 'Neighbourhood guides for Accra, Kumasi, Cape Coast, and beyond.' },
      { id: 'travel_domestic', label: 'Domestic Tourism', description: 'Explore hidden gems from Mole to the Volta highlands.' },
      { id: 'travel_festival_tours', label: 'Festival & Heritage Tours', description: 'Homowo, Hogbetsotso, Chale Wote, PANAFEST, and more.' },
    ],
  },
  {
    id: 'culture',
    label: 'Culture & Heritage',
    description: 'Traditions, stories, and creative expressions from home and afar.',
    icon: Feather,
    subcategories: [
      { id: 'culture_history', label: 'History & Archives', description: 'Documenting Ghana’s history, archives, and museums.' },
      { id: 'culture_language', label: 'Languages & Dialects', description: 'Twi, Ewe, Ga, Dagbani, Hausa, Nzema, and more.' },
      { id: 'culture_traditions', label: 'Traditions & Rituals', description: 'Naming ceremonies, royal courts, and rites of passage.' },
      { id: 'culture_pop', label: 'Pop Culture & Trends', description: 'Film, fashion, digital culture, and pop commentary.' },
      { id: 'culture_current_affairs', label: 'Current Affairs & Commentary', description: 'Analyses on policy, society, and national discourse.' },
      { id: 'culture_festivals', label: 'Festivals & Celebrations', description: 'Homowo, Odwira, Kundum, and Ga Mashie street festivals.' },
      { id: 'culture_kente', label: 'Craft & Kente Heritage', description: 'Weaving, beadwork, and craftsmanship traditions.' },
      { id: 'culture_storytelling', label: 'Storytelling & Oral History', description: 'Folklore nights, poetry, and griot traditions.' },
      { id: 'culture_diaspora_returns', label: 'Year of Return & Beyond', description: 'Diaspora homecoming stories and cultural exchange.' },
    ],
  },
  {
    id: 'arts',
    label: 'Arts & Creative',
    description: 'From studio to stage—showcase and refine your craft.',
    icon: Palette,
    subcategories: [
      { id: 'arts_visual', label: 'Visual Arts', description: 'Painters, sculptors, galleries, and art fairs.' },
      { id: 'arts_performing', label: 'Performing Arts', description: 'Theatre, dance troupes, and performance showcases.' },
      { id: 'arts_design', label: 'Design & Illustration', description: 'Graphic designers, illustrators, and digital artists.' },
      { id: 'arts_storytelling', label: 'Storytelling & Writing', description: 'Authors, poets, playwrights, and script labs.' },
      { id: 'arts_photography', label: 'Photography & Film', description: 'Photo walks, filmmaking workshops, and cinematography.' },
      { id: 'arts_crafts', label: 'Crafts & Making', description: 'Woodwork, bead making, pottery, and handmade goods.' },
      { id: 'arts_textiles', label: 'Textiles & Fashion Craft', description: 'Kente, batik, smock weaving, and fashion labs.' },
      { id: 'arts_spoken_word', label: 'Spoken Word & Poetry', description: 'Mic sessions, poetry collectives, and slam events.' },
    ],
  },
  {
    id: 'music',
    label: 'Music & Performance',
    description: 'Bands, choirs, playlists, and live sessions.',
    icon: Music,
    subcategories: [
      { id: 'music_gospel', label: 'Gospel & Worship', description: 'Choirs, praise nights, and worship collectives.' },
      { id: 'music_highlife', label: 'Highlife & Palmwine', description: 'Highlife legends, live bands, and palmwine sessions.' },
      { id: 'music_hiplife', label: 'Hiplife & Hip-Hop', description: 'Recording tips, cyphers, and lyricist meetups.' },
      { id: 'music_afrobeats', label: 'Afrobeats & Amapiano', description: 'Studio collabs, beatmakers, and DJ communities.' },
      { id: 'music_traditional_drumming', label: 'Traditional Drumming & Dance', description: 'Fontomfrom, borborbor, kete, and drum circles.' },
      { id: 'music_classical', label: 'Classical & Orchestral', description: 'Choirs, orchestras, and music theory circles.' },
      { id: 'music_jazz', label: 'Jazz & Soul', description: 'Jam sessions, live lounges, and soulful performances.' },
      { id: 'music_indie', label: 'Indie & Alternative', description: 'Indie artists, live sessions, and intimate gigs.' },
      { id: 'music_world', label: 'Global Sounds', description: 'Cross-cultural collaborations and global influences.' },
    ],
  },
  {
    id: 'media',
    label: 'Media & Storytelling',
    description: 'Podcasts, newsletters, journalism, and media craft.',
    icon: Clapperboard,
    subcategories: [
      { id: 'media_journalism', label: 'Journalism & Reporting', description: 'Newsrooms, investigative desks, and campus press.' },
      { id: 'media_podcasts', label: 'Podcasts & Audio', description: 'Podcast production, audio storytelling, and sound design.' },
      { id: 'media_newsletters', label: 'Newsletters & Publishing', description: 'Newsletter builders, editorial calendars, and publishing tips.' },
      { id: 'media_strategy', label: 'Content Strategy', description: 'Editorial ops, content calendars, and analytics.' },
      { id: 'media_documentary', label: 'Documentary & Film', description: 'Documentary storytelling, docu-series, and field production.' },
      { id: 'media_local_radio', label: 'Radio & Broadcast', description: 'Campus radio, community FM, and broadcast storytelling.' },
      { id: 'media_social', label: 'Digital & Social Media', description: 'Influencer strategy, digital communities, and live streaming.' },
    ],
  },
  {
    id: 'gaming',
    label: 'Gaming & Esports',
    description: 'Competitive scenes, game design, and streaming communities.',
    icon: Gamepad2,
    subcategories: [
      { id: 'gaming_esports', label: 'Esports & Competition', description: 'FIFA leagues, eSoccer championships, and tournaments.' },
      { id: 'gaming_game_design', label: 'Game Design & Development', description: 'Game dev meetups, game jams, and testing sessions.' },
      { id: 'gaming_indie', label: 'Indie Games', description: 'Indie studios, prototypes, and storytelling games.' },
      { id: 'gaming_streaming', label: 'Streaming & Content', description: 'Twitch, YouTube, and live-streaming collectives.' },
      { id: 'gaming_tabletop', label: 'Tabletop & Roleplay', description: 'Board games, roleplay groups, and community nights.' },
      { id: 'gaming_mobile', label: 'Mobile & Casual Gaming', description: 'Mobile esports, hyper-casual games, and gaming lounges.' },
      { id: 'gaming_fifa', label: 'FIFA & Sports Titles', description: 'FIFA tournaments, PES battles, and sports gamer communities.' },
    ],
  },
  {
    id: 'outdoors',
    label: 'Outdoors & Nature',
    description: 'Explore, conserve, and storytell the natural world.',
    icon: Trees,
    subcategories: [
      { id: 'outdoors_hiking', label: 'Hiking & Trekking', description: 'Aburi hills, Afadjato climbs, and guided trails.' },
      { id: 'outdoors_camping', label: 'Camping & Overlanding', description: 'Camping, glamping, and overlanding meetups.' },
      { id: 'outdoors_conservation', label: 'Conservation Projects', description: 'Tree planting, wildlife sanctuaries, and conservation clubs.' },
      { id: 'outdoors_photography', label: 'Nature Photography', description: 'Wildlife, landscape, and travel photography tours.' },
      { id: 'outdoors_water', label: 'Water & Marine Adventures', description: 'Kayaking, surfing, river safaris, and island escapes.' },
      { id: 'outdoors_ecotourism', label: 'Eco-Tourism & Community Travel', description: 'Community eco-lodges and responsible tourism.' },
      { id: 'outdoors_volta', label: 'Volta & Northern Adventures', description: 'Waterfalls, caves, and northern Ghana expeditions.' },
      { id: 'outdoors_safari', label: 'Safari & Wildlife', description: 'Mole National Park, Shai Hills, and safaris.' },
    ],
  },
  {
    id: 'culinary',
    label: 'Culinary & Food',
    description: 'Recipes, food ventures, and global food cultures.',
    icon: Utensils,
    subcategories: [
      { id: 'culinary_recipes', label: 'Recipes & Home Cooking', description: 'Home cooking, meal prep, and culinary swaps.' },
      { id: 'culinary_baking', label: 'Baking & Pastry', description: 'Cake studios, pastry labs, and dessert artistry.' },
      { id: 'culinary_food_culture', label: 'Food Culture & Travel', description: 'Food heritage, culinary tourism, and food storytelling.' },
      { id: 'culinary_enterprise', label: 'Food Entrepreneurship', description: 'Food trucks, catering, and agrifood startups.' },
      { id: 'culinary_wellness', label: 'Nutrition & Wellness', description: 'Healthy eating, dietetics, and meal plans.' },
      { id: 'culinary_ghanaian_classics', label: 'Ghanaian Classics', description: 'Fufu hacks, waakye secrets, banku pairings, and local staples.' },
      { id: 'culinary_street_food', label: 'Street Food & Night Markets', description: 'Kelewele, chaw, and street food culture.' },
      { id: 'culinary_cocoa', label: 'Cocoa & Beverage Craft', description: 'Chocolate makers, beverage artisans, and coffee culture.' },
    ],
  },
  {
    id: 'hobbies',
    label: 'Hobbies & Leisure',
    description: 'Clubs, collections, and playful downtime across Ghana.',
    icon: Puzzle,
    subcategories: [
      { id: 'hobbies_book_clubs', label: 'Book & Reading Clubs', description: 'Book swaps, literature circles, and campus reading pods.' },
      { id: 'hobbies_diy_crafts', label: 'DIY & Crafts', description: 'Handmade decor, upcycling, and weekend craft sessions.' },
      { id: 'hobbies_collectibles', label: 'Collectibles & Memorabilia', description: 'Comic lovers, jersey collectors, and memorabilia swaps.' },
      { id: 'hobbies_gardening', label: 'Gardening & Plant Life', description: 'Balcony gardens, community farms, and plant parents.' },
      { id: 'hobbies_travel_groups', label: 'Weekend Travel Crews', description: 'Road trips, backpacking buddies, and tour clubs.' },
      { id: 'hobbies_board_games', label: 'Board & Card Games', description: 'Board game nights, chess clubs, and card battles.' },
      { id: 'hobbies_cultural_clubs', label: 'Cultural & Interest Clubs', description: 'Debate societies, film buffs, and language meetups.' },
    ],
  },
  {
    id: 'sports',
    label: 'Sports & Teams',
    description: 'Match recaps, coaching, fandom, and player development.',
    icon: Trophy,
    subcategories: [
      { id: 'sports_soccer', label: 'Football (Soccer)', description: 'GPL, Black Stars, Sunday league, and academy updates.' },
      { id: 'sports_womens_football', label: 'Women’s Football', description: 'Black Queens, universities, and community clubs.' },
      { id: 'sports_athletics', label: 'Athletics & Track', description: 'Sprinting, marathon training, and athletics meets.' },
      { id: 'sports_boxing', label: 'Boxing & Combat Sports', description: 'Bukom boxing gyms, MMA, taekwondo, and karate.' },
      { id: 'sports_basketball', label: 'Basketball', description: 'B-ball leagues, 3x3 tournaments, and campus competitions.' },
      { id: 'sports_volleyball', label: 'Volleyball & Beach Sports', description: 'Beach volleyball and volleyball clubs.' },
      { id: 'sports_table_tennis', label: 'Table Tennis & Badminton', description: 'Spin training, club nights, and tournaments.' },
      { id: 'sports_tennis', label: 'Tennis & Racquet Sports', description: 'Tennis clubs, squash courts, and coaching clinics.' },
      { id: 'sports_golf', label: 'Golf & Country Clubs', description: 'Golf societies, tournaments, and driving ranges.' },
      { id: 'sports_swimming', label: 'Swimming & Aquatics', description: 'Swim clubs, lifesaving, and water sports.' },
      { id: 'sports_parasports', label: 'Para Sports & Inclusion', description: 'Adaptive sports, inclusive leagues, and support networks.' },
      { id: 'sports_cycling', label: 'Cycling & Adventure Rides', description: 'Road cycling, MTB trails, and cross-country rides.' },
    ],
  },
  {
    id: 'spirituality',
    label: 'Faith & Values',
    description: 'Faith journeys, devotionals, and reflections on purpose.',
    icon: Sparkles,
    subcategories: [
      { id: 'spirituality_faith', label: 'Faith Communities', description: 'Church cells, mosque fellowships, and faith movements.' },
      { id: 'spirituality_devotion', label: 'Devotionals & Reflections', description: 'Daily devotionals, scripture sharing, and reflections.' },
      { id: 'spirituality_interfaith', label: 'Interfaith Dialogue', description: 'Dialogue across faith traditions and unity movements.' },
      { id: 'spirituality_service', label: 'Spiritual Service & Missions', description: 'Ministry work, outreach, and mission trips.' },
      { id: 'spirituality_prayer_camps', label: 'Prayer Camps & Retreats', description: 'Retreat centres, revival grounds, and quiet spaces.' },
      { id: 'spirituality_praise_music', label: 'Praise & Music Ministries', description: 'Choirs, praise teams, and gospel artistry.' },
    ],
  },
] as const;

export type InterestCategoryId = (typeof INTEREST_LIBRARY)[number]['id'];

type SubcategoryUnion = (typeof INTEREST_LIBRARY)[number]['subcategories'];

export type InterestSubcategoryId = SubcategoryUnion extends readonly (infer Sub)[]
  ? Sub extends { id: infer Id }
    ? Id extends string
      ? Id
      : never
    : never
  : never;

export type InterestOptionId = InterestCategoryId | InterestSubcategoryId;

export const ALL_INTEREST_IDS: readonly InterestOptionId[] = (() => {
  const ids = new Set<InterestOptionId>();
  INTEREST_LIBRARY.forEach((category) => {
    ids.add(category.id);
    category.subcategories?.forEach((sub) => ids.add(sub.id));
  });
  return Array.from(ids);
})();
